# Generated by Django 4.2.7 on 2023-11-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, max_length=255, null=True)),
                ("multiuser", models.IntegerField()),
                ("start_date", models.CharField(blank=True, max_length=255, null=True)),
                ("end_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_one_connect",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("customer_user", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("traffic", models.IntegerField()),
                ("referral", models.CharField(blank=True, max_length=255, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssh_port", models.CharField(blank=True, max_length=255, null=True)),
                ("tls_port", models.CharField(blank=True, max_length=255, null=True)),
                ("t_token", models.CharField(blank=True, max_length=255, null=True)),
                ("t_id", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("multiuser", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status_multiuser",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("home_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download", models.CharField(default=0, max_length=255)),
                ("upload", models.CharField(default=0, max_length=255)),
                ("total", models.CharField(default=0, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_entries",
                        to="api.client",
                        to_field="username",
                    ),
                ),
            ],
            options={
                "unique_together": {("username",)},
            },
        ),
    ]
